// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/spotify": {
    params: {};
  };
  "/auth/spotify/callback": {
    params: {};
  };
  "/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/spotify" | "/auth/spotify/callback" | "/logout";
  };
  "routes/auth.spotify.tsx": {
    id: "routes/auth.spotify";
    page: "/auth/spotify" | "/auth/spotify/callback";
  };
  "routes/auth.spotify.callback.tsx": {
    id: "routes/auth.spotify.callback";
    page: "/auth/spotify/callback";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth.spotify": typeof import("./app/routes/auth.spotify.tsx");
  "routes/auth.spotify.callback": typeof import("./app/routes/auth.spotify.callback.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
};