// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playlists/:playlistId": {
    params: {
      "playlistId": string;
    };
  };
  "/index-action-helpers": {
    params: {};
  };
  "/index-action-helpers/test": {
    params: {};
  };
  "/api/spotify-search": {
    params: {};
  };
  "/artists/:artistId": {
    params: {
      "artistId": string;
    };
  };
  "/albums/:albumId": {
    params: {
      "albumId": string;
    };
  };
  "/auth/callback": {
    params: {};
  };
  "/index-helpers": {
    params: {};
  };
  "/index-helpers/test": {
    params: {};
  };
  "/auth/spotify": {
    params: {};
  };
  "/auth/spotify/callback": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/collections/:collectionId": {
    params: {
      "collectionId": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/dev": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/playlists/:playlistId" | "/index-action-helpers" | "/index-action-helpers/test" | "/api/spotify-search" | "/artists/:artistId" | "/albums/:albumId" | "/auth/callback" | "/index-helpers" | "/index-helpers/test" | "/auth/spotify" | "/auth/spotify/callback" | "/collections" | "/collections/:collectionId" | "/auth/login" | "/auth/dev" | "/discover" | "/health" | "/logout";
  };
  "routes/playlists.$playlistId.tsx": {
    id: "routes/playlists.$playlistId";
    page: "/playlists/:playlistId";
  };
  "routes/index-action-helpers.ts": {
    id: "routes/index-action-helpers";
    page: "/index-action-helpers" | "/index-action-helpers/test";
  };
  "routes/index-action-helpers.test.ts": {
    id: "routes/index-action-helpers.test";
    page: "/index-action-helpers/test";
  };
  "routes/api.spotify-search.ts": {
    id: "routes/api.spotify-search";
    page: "/api/spotify-search";
  };
  "routes/artists.$artistId.tsx": {
    id: "routes/artists.$artistId";
    page: "/artists/:artistId";
  };
  "routes/albums.$albumId.tsx": {
    id: "routes/albums.$albumId";
    page: "/albums/:albumId";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/index-helpers.ts": {
    id: "routes/index-helpers";
    page: "/index-helpers" | "/index-helpers/test";
  };
  "routes/index-helpers.test.ts": {
    id: "routes/index-helpers.test";
    page: "/index-helpers/test";
  };
  "routes/auth.spotify.tsx": {
    id: "routes/auth.spotify";
    page: "/auth/spotify" | "/auth/spotify/callback";
  };
  "routes/auth.spotify.callback.tsx": {
    id: "routes/auth.spotify.callback";
    page: "/auth/spotify/callback";
  };
  "routes/collections.tsx": {
    id: "routes/collections";
    page: "/collections" | "/collections/:collectionId";
  };
  "routes/collections.$collectionId.tsx": {
    id: "routes/collections.$collectionId";
    page: "/collections/:collectionId";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.dev.tsx": {
    id: "routes/auth.dev";
    page: "/auth/dev";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/health.ts": {
    id: "routes/health";
    page: "/health";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/playlists.$playlistId": typeof import("./app/routes/playlists.$playlistId.tsx");
  "routes/index-action-helpers": typeof import("./app/routes/index-action-helpers.ts");
  "routes/index-action-helpers.test": typeof import("./app/routes/index-action-helpers.test.ts");
  "routes/api.spotify-search": typeof import("./app/routes/api.spotify-search.ts");
  "routes/artists.$artistId": typeof import("./app/routes/artists.$artistId.tsx");
  "routes/albums.$albumId": typeof import("./app/routes/albums.$albumId.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/index-helpers": typeof import("./app/routes/index-helpers.ts");
  "routes/index-helpers.test": typeof import("./app/routes/index-helpers.test.ts");
  "routes/auth.spotify": typeof import("./app/routes/auth.spotify.tsx");
  "routes/auth.spotify.callback": typeof import("./app/routes/auth.spotify.callback.tsx");
  "routes/collections": typeof import("./app/routes/collections.tsx");
  "routes/collections.$collectionId": typeof import("./app/routes/collections.$collectionId.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.dev": typeof import("./app/routes/auth.dev.tsx");
  "routes/discover": typeof import("./app/routes/discover.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/health": typeof import("./app/routes/health.ts");
  "routes/logout": typeof import("./app/routes/logout.tsx");
};